#!/usr/bin/env perl

use warnings;
use strict;

use lib "../";
use Util;

use Test::More;

require_ok( './day07.pl' );

sub test_input {
    return <<"INPUT";
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
INPUT
}

subtest 'Day 01 Part 1' => sub {
    my $input = Util::grid( test_input() );
    is( part1( $input ), 21, 'Correct result' );
};

subtest 'Day 01 Part 2' => sub {
    my $input = Util::grid( test_input() );
    is( part2( $input ), 40, 'Correct result' );
};

done_testing();
